# Generated by Django 4.1.2 on 2022-10-04 13:47

from django.db import migrations, models
import shortening.models


class Migration(migrations.Migration):

    dependencies = [
        ('shortening', '0002_alter_clientdata_client_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalurldata',
            name='url',
            field=models.URLField(unique=True, validators=[shortening.models.OptionalSchemeURLValidator()]),
        ),
    ]
