# Generated by Django 4.1.2 on 2022-10-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortening', '0003_alter_originalurldata_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalurldata',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
